default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:

development:
  <<: *default
  database: encore_beat_development

test:
  <<: *default
  database: encore_beat_test

production:
  <<: *default
  database: encore_beat_production
