# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51f831d1c49780b82838ab8d3f08d13366f91770c57cfb3f2cd390e4f54457ee239fb0d1498ad38d623fa244bd88585077aa7eb2472ed1a52f09d9f365414b98

test:
  secret_key_base: 64f0ade361202083fd6896dafad018929194a4eb60e480ad3fde791eff20e1dc71bede675ce6bae72e5cf10a4ae785d7cab7da046844c44318765cd0d8bf2c0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
